# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Unifi SMS Gateway
version: "0.0.6"
slug: unifi-sms-gateway
description: Unifi SMS Gateway add-on
url: "https://github.com/kiall/unifi-sms-gateway"
image: "ghcr.io/kiall/{arch}-addon-unifi-sms-gateway"
startup: services
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
ports:
  8585/tcp: 8585
schema:
  unifi_ip: "str"
  unifi_user: "str"
  unifi_password: "password"
  api_key: "password"
