# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Unifi SMS Gateway
version: "0.0.1"
slug: Unifi SMS Gateway
description: Unifi SMS Gateway add-on
url: "https://github.com/kiall/unifi-sms-gateway"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/kiall/{arch}-addon-unifi-sms-gateway"