# Loads default set of integrations. Do not remove.
default_config:

# Enable logging
logger:
  default: info
  logs:
    custom_components.unifi_sms_gateway: debug

automation: !include automations.yaml